image: node:latest

variables:
  PUBLIC_URL: /event-management/frontend

cache:
  paths:
    - frontend/node_modules

stages:
  - deploy

pages:
  stage: deploy

  script:
    - cd frontend        # Navigate to the frontend directory
    - npm install        # Install all dependencies
    - npm run build      # Build for prod
    - mv build ../public # Move build files to public dir for Gitlab Pages, assuming you are in the frontend directory

  artifacts:
    paths:
      - public  # Include the public/ folder in the artifacts

  only:
    - main
