image: node:latest

variables:
  PUBLIC_URL: /event-management/frontend

cache:
  paths:
    - frontend/node_modules

stages:
  - deploy

pages:
  stage: deploy

  script:
    - cd frontend        # Navigate to the frontend directory
    - npm install        # Install all dependencies
    - npm run build      # Build for prod

  artifacts:
    paths:
      - frontend/build   # Include the build/ folder in the artifacts

  only:
    - main
